### ISSUE TITLE
jira bulk update breaks documents with custom fields

### ISSUE THREAD

**Issue by chrysanthoslianos** [chaoss/grimoirelab-elk#912] opened 2020-07-10 11:46 UTC
Hi community. I have been using Grimoirelab for a while now.
I am working on a custom python3 app, whose purpose is to fetch docs from the Jira ES index, and add some computed fields.
All is well until the bulk update operation takes over (as scheduled), and my computed fields go missing.
Is there a way to persist Jira index when migrating over from Jira-raw?

Thanks in advance,
Chrys

**Comment by alpgarcia** [comment] 2020-07-10 14:11
If I understood it correctly, you are modifying the enriched index. If so, the problem is that updates on that index will overwrite your changes, even in incremental mode, some documents will be overwritten and, as they are created from the raw index, all the info you could have added to the enriched documents would be overwritten. In this case, I think the right solution would be to create a new index instead of using the existing one. 

What I would do is to create a study. Studies run on top of raw or enriched indexes and generate new indexes. This way you would have your code in the loop, and you can control your custom fields as you wish.

Maybe I didn't understand your problem, or @valeriocos could suggest a different option.

**Comment by chrysanthoslianos** [comment] 2020-07-10 14:18
@alpgarcia  I am doing the exact thing you are describing. 
Will studies work for calculated fields? The documents' fields I am indexing are calculated externally, not from the data already provided by Grimoire

**Comment by alpgarcia** [comment] 2020-07-10 14:54
On the one hand, we would need to know what you need to calculate those fields. Are there any dependencies from external sources or are we talking about just calculations?

On the other hand, studies make sense if we are adding information that could be interesting for others. If it was something really specific, it is probably better to just write a separate script to create a new index outside GrimoireLab. Could you tell us a bit more about your use case?

About studies, the idea is adding information to indexes. You can see what studies are available for Git here:
https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/enriched/git.py#L94

Some of them generate new indexes to store the data, others like demography update the already existing index. I'd say the best approach is always generating a new index when trying to solve specific problems. The areas of code study, for instance, uses directly the raw index, so you are not limited to use the enriched indexes only.

I would suggest you have a look at these studies and try to find if any of them seems to do something similar to what you need to achieve.

**Comment by chrysanthoslianos** [comment] 2020-07-13 08:46
Thanks for the reply. My use case is to calculate jira worklogs, thus using the Jira index to fetch unique issues and then calculate worklogs via the jira-py library, appending the data to the existing documents. 
Do you think studies would work for such a scenario?

**Comment by alpgarcia** [comment] 2020-07-14 07:53
As far as I know, the enriched Jira index includes `time_*` fields (https://github.com/chaoss/grimoirelab-elk/blob/master/schema/jira.csv#L70, https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/enriched/jira.py#L295). Is there any other information you need from the Jira API?

**Comment by chrysanthoslianos** [comment] 2020-07-14 08:00
Yes, timespent received from Jira is not accurate for my use case, hence why I interact with the Jira worklogs.

**Comment by alpgarcia** [comment] 2020-07-14 09:45
@valeriocos wdyt? should this be a study or (part of) a Perceval backend?

**Comment by valeriocos** [comment] 2020-07-14 12:40
Hi @chrysanthoslianos @alpgarcia ,

An option could be to use the `extra_data` study (ref [here](https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/enriched/enrich.py#L1066)). This study enables adding (or removing) extra fields to a target index. 
The extra data to be added/removed is passed via a JSON and contains:
- a list of AND `conditions`, which must be all True to select a document. Each condition is defined by a `field` present in the document and a `value`.
- an optional `date_range`, used to apply the conditions on a time span. Date range is defined by a datetime `field`, a `start` and optional an `end` date.
- a list of `set_extra_fields`, which will be set (i.e., added or modified) on the target index. An `add_extra_field` is defined by a `field` and its `value`. Field names are automatically prepended with the word `extra`. This is needed to separate the original fields with the extra ones.
An example of JSON is provided below:
```
        [
            {
                "conditions": [
                    {
                        "field": "author_name",
                        "value": "Mister X"
                    }
                ],
                "set_extra_fields": [
                    {
                        "field": "maintainer",
                        "value": "true"
                    }
                ]
            }
        ]
```

The JSON can be passed to the platform using the setup.cfg, an example is available at: https://github.com/chaoss/grimoirelab-sirmordred#git-

```
[git]
raw_index = git_raw
enriched_index = git_enriched
latest-items = true
studies = [enrich_extra_data:git] 

[enrich_extra_data:git]
json_url = https://gist.githubusercontent.com/zhquan/bb48654bed8a835ab2ba9a149230b11a/raw/5eef38de508e0a99fa9772db8aef114042e82e47/bitergia-example.txt
```

In order to activate the extra data study for Jira, you need to modify the code at https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/enriched/jira.py by redefining the init method (as similarly done for [git](https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/enriched/git.py#L88) and [github](https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/enriched/github.py#L102))
```
def __init__(self, db_sortinghat=None, db_projects_map=None, json_projects_map=None,
                 db_user='', db_password='', db_host=''):
        super().__init__(db_sortinghat, db_projects_map, json_projects_map,
                         db_user, db_password, db_host)

        self.studies = []
        self.studies.append(self.enrich_extra_data)
```

Hope this helps

**Comment by chrysanthoslianos** [comment] 2020-07-14 12:46
@valeriocos  That was very insightful, appreciate both yours and @alpgarcia 's time and effort! For now, reindexing does what I need, but the steps you outlined look useful for the long term, since we are planning on building Grimoire within our premises!

**Comment by fioddor** [comment] 2022-02-14 13:18
Can we close this issue then, @chrysanthoslianos?

**Comment by chrysanthoslianos** [comment] 2022-02-14 13:21
@fioddor  yes of course!

**Comment by vchrombie** [comment] 2022-02-14 13:23
Thank you everyone for helping with solving this issue!

**Closed as completed by vchrombie** 2022-02-14 13:23 UTC
