### ISSUE TITLE
[studies] Access to Elasticsearch via SSL not verifying certs

### ISSUE THREAD

**Issue by jgbarah** [chaoss/grimoirelab-elk#369] opened 2018-06-05 21:32 UTC
For all datasources, when access to Elasticsearch (either for enriched or raw indexes) is done via SSL, we have an option to avoid checking certificates. That's useful when we're accessing an Elasticsearch instance with, for example, a self-signed certificate.

But for studies, it seems we don't have something similar. That means we cannot run studies when Elasticsearch is accessed like that.

So, I think we should have that option when studies are reading or writing to such indexes...

**Comment by valeriocos** [comment] 2018-07-12 13:05
@jgbarah , is it possible that this issue has been already solved/addressed?
I remember that @alpgarcia did some work on it:
- https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/enriched/git.py#L832 (areas of code)
- https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/enriched/git.py#L664 (demography)
- https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/enriched/enrich.py#L849 (onion)

kafka_kip doesn't seem to need it (https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/enriched/mbox_study_kip.py)

**Comment by alpgarcia** [comment] 2018-07-17 16:47
This seems to be a duplicate of #363

**Comment by valeriocos** [comment] 2019-07-26 14:51
Fixed with https://github.com/chaoss/grimoirelab-elk/pull/392

**Closed as completed by valeriocos** 2019-07-26 14:51 UTC
