### ISSUE TITLE
UnknownTimezoneWarning

### ISSUE THREAD

**Issue by jsmanrique** [chaoss/grimoirelab-elk#722] opened 2019-11-05 21:46 UTC
I think this has been reported before, and it's related with some mailing lists analysis.

I am getting a lot of warning messages in mordred logs like these ones:
```
mordred_1        | /usr/local/lib/python3.5/dist-packages/dateutil/parser/_parser.py:1206: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.
mordred_1        |   category=UnknownTimezoneWarning)
mordred_1        | /usr/local/lib/python3.5/dist-packages/dateutil/parser/_parser.py:1206: UnknownTimezoneWarning: tzname BST identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.
mordred_1        |   category=UnknownTimezoneWarning)
mordred_1        | /usr/local/lib/python3.5/dist-packages/dateutil/parser/_parser.py:1206: UnknownTimezoneWarning: tzname MET identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.
mordred_1        |   category=UnknownTimezoneWarning)
mordred_1        | /usr/local/lib/python3.5/dist-packages/dateutil/parser/_parser.py:1206: UnknownTimezoneWarning: tzname PST identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.
mordred_1        |   category=UnknownTimezoneWarning)
mordred_1        | /usr/local/lib/python3.5/dist-packages/dateutil/parser/_parser.py:1206: UnknownTimezoneWarning: tzname EST identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.
mordred_1        |   category=UnknownTimezoneWarning)
mordred_1        | /usr/local/lib/python3.5/dist-packages/dateutil/parser/_parser.py:1206: UnknownTimezoneWarning: tzname IDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.
mordred_1        |   category=UnknownTimezoneWarning)
mordred_1        | /usr/local/lib/python3.5/dist-packages/dateutil/parser/_parser.py:1206: UnknownTimezoneWarning: tzname PDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.
mordred_1        |   category=UnknownTimezoneWarning)
mordred_1        | /usr/local/lib/python3.5/dist-packages/dateutil/parser/_parser.py:1206: UnknownTimezoneWarning: tzname MDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.
mordred_1        |   category=UnknownTimezoneWarning)
mordred_1        | /usr/local/lib/python3.5/dist-packages/dateutil/parser/_parser.py:1206: UnknownTimezoneWarning: tzname MST identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.
mordred_1        |   category=UnknownTimezoneWarning)
mordred_1        | /usr/local/lib/python3.5/dist-packages/dateutil/parser/_parser.py:1206: UnknownTimezoneWarning: tzname IST identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.
mordred_1        |   category=UnknownTimezoneWarning)
mordred_1        | /usr/local/lib/python3.5/dist-packages/dateutil/parser/_parser.py:1206: UnknownTimezoneWarning: tzname CST identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.
mordred_1        |   category=UnknownTimezoneWarning)
```

It seems that the message includes the solution:
```Pass  `tzinfos` argument in order to correctly return a timezone-aware datetime```

And the thing that worries me is this part:
`In a future version, this will raise an exception`

So, perhaps it would be great to have it solved before that *future version* of [dateutil](https://dateutil.readthedocs.io/en/stable/) arrives.

**Comment by jsmanrique** [comment] 2019-11-05 21:51
Oh, I see this a duplicated issue: chaoss/grimoirelab-toolkit#12

**Comment by valeriocos** [comment] 2019-11-06 06:36
If possible, can you provide the log where this warning is thrown? 
Ideally all this kind of calls should pass by grimoirelab-toolkit. Having the line causing the problem would be great.

Are you running grimoirelab from docker/docker-compose or locally?

Thanks

**Comment by jsmanrique** [comment] 2019-11-06 07:11
I am running the docker-compose grimoirelab with this set up:
https://gitlab.com/jsmanrique/grimoirelab-demo-for-gnome

I think it is related with `pipermail` data source.

I have pasted the log lines with the warning message. What do you mean by "the log where this warning is thrown"?

Thank you

**Comment by valeriocos** [comment] 2019-11-06 07:51
Thanks for the info. The log messages are just about dateutil code and I was wondering if you had some hints about the GrimoireLab code.

Anyway I'll check it out today and report.

**Comment by jsmanrique** [comment] 2019-11-06 07:53
I don't have any hint. Thank you @valeriocos

**Comment by valeriocos** [comment] 2019-11-06 08:36
I'm trying to replicate the error using the projects.json you passed. It's possible that the recent update in the dateutil package ([released](https://pypi.org/project/python-dateutil/) Nov 3rd) is the responsible of it.
Can you add here the python-dateutil version you are using? thanks

**Comment by valeriocos** [comment] 2019-11-06 14:50
I would pin the dependency of python-dateutil to 2.8.0 (in Perceval and toolkit) to avoid having an error in the future.

It seems that the warning can be removed by passing a dict of timezones with the corresponding values in UTC (https://stackoverflow.com/questions/51206500/how-to-convert-a-string-datetime-with-unknown-timezone-to-timestamp-in-python), however the solution doesn't look really clean.

**Comment by sduenas** [comment] 2019-11-06 16:18
@jsmanrique can you give us the list of packages you're using when you get this error?. You can run `pip freeze` (inside of your environment if you use one) and paste the output here.

**Comment by jsmanrique** [comment] 2019-11-08 07:49
> @jsmanrique can you give us the list of packages you're using when you get this error?. You can run `pip freeze` (inside of your environment if you use one) and paste the output here.

I am using docker-compose installation, but let's see if this is what you are looking for:
```
root@gnome-58252787:~/grimoirelab-for-demos# docker exec -i -t grimoirelab-for-demos_mordred_1 /bin/bash                              
bitergia@e1620d75c4c1:~$ pip freeze                                                                                                   astroid==2.3.2                                                                                                                        
bandit==1.6.2                                                                                                                         beautifulsoup4==4.8.1                                                                                                                 brewer2mpl==1.4.1                                                                                                                     cereslib==0.1.8                                                                                                                       certifi==2019.9.11                                                                                                                    chardet==3.0.4                                                                                                                        cheroot==8.2.1                                                                                                                        CherryPy==18.3.0                                                                                                                      
Click==7.0                                                                                                                            
cycler==0.10.0                                                                                                                        decorator==4.4.1                                                                                                                      dulwich==0.18.6                                                                                                                       elasticsearch==6.3.1                                                                                                                  elasticsearch-dsl==6.3.1                                                                                                              entrypoints==0.3                                                                                                                      feedparser==6.0.0b1                                                                                                                   flake8==3.7.8                                                                                                                         
gitdb2==2.0.6                                                                                                                         GitPython==3.0.4                                                                                                                      graal==0.2.3
grimoire-elk==0.63.0                                                                                                                  grimoirelab==0.2.32                                                                                                                   grimoirelab-panels==0.0.44                                                                                                            grimoirelab-toolkit==0.1.10                                                                                                           idna==2.8                                                                                                                             
isort==4.3.21                                                                                                                         jaraco.functools==2.0                                                                                                                 Jinja2==2.10.3                                                                                                                        kidash==0.4.15                                                                                                                        kingarthur==0.1.18                                                                                                                    kiwisolver==1.1.0                                                                                                                     
lazy-object-proxy==1.4.3                                                                                                              lizard==1.16.6                                                                                                                        manuscripts==0.2.20                                                                                                                   MarkupSafe==1.1.1                                                                                                                     matplotlib==3.0.3                                                                                                                     mccabe==0.6.1                                                                                                                         
more-itertools==7.2.0                                                                                                                 networkx==2.4
numpy==1.17.3                                                                                                                         pandas==0.22.0                                                                                                                        
pbr==5.4.3                                                                                                                            perceval==0.12.24
perceval-finos==0.1.6                                                                                                                 
perceval-mozilla==0.2.9                                                                                                               
perceval-opnfv==0.1.16                                                                                                                
perceval-puppet==0.1.15
portend==2.5                                                                                                                          prettyplotlib==0.1.7                                                                                                                  pycodestyle==2.5.0                                                                                                                    pydot==1.4.1
pyflakes==2.1.1                                                                                                                       
pylint==2.4.3
PyMySQL==0.9.3                                                                                                                        pyparsing==2.4.2
python-dateutil==2.8.0                                                                                                                pytz==2019.3                                                                                                                          PyYAML==5.1.2                                                                                                                         redis==2.10.6
requests==2.21.0                                                                                                                      
rq==1.0                                                                                                                               
scipy==1.3.1                                                                                                                          sgmllib3k==1.0.0
sirmordred==0.2.25                                                                                                                    six==1.12.0                                                                                                                           smmap2==2.0.5                                                                                                                         sortinghat==0.7.7
soupsieve==1.9.4                                                                                                                      SQLAlchemy==1.3.10                                                                                                                    stevedore==1.31.0                                                                                                                     tempora==1.14.1
typed-ast==1.4.0                                                                                                                      urllib3==1.24.3                                                                                                                       wrapt==1.11.2                                                                                                                         zc.lockfile==2.0
```

**Comment by sduenas** [comment] 2019-11-08 08:11
According to the previous post, @jsmanrique is using **python-dateutil 2.8**, so I guess that's not the cause of the problem. Don't you think @valeriocos?

**Comment by valeriocos** [comment] 2019-11-08 08:28
The idea of pinning `python-dateutil 2.8` is to avoid an exception in the future. The warning is originated in here: https://github.com/dateutil/dateutil/blob/2.8.0/dateutil/parser/_parser.py#L1201

**Comment by sduenas** [comment] 2019-11-08 09:04
That's doesn't worry me much. I always prefer to have an exception which I'll have to manage than something that hides the error.

**Comment by valeriocos** [comment] 2019-11-08 09:09
ok, sound good. What do we do with the warning? 

The solution proposed here: https://github.com/chaoss/grimoirelab-elk/issues/722#issuecomment-550343679 isn't really clean.

**Comment by sduenas** [comment] 2019-11-08 16:54
@valeriocos do we know what part of the code this is happening? I'd like to have the exact date that is wrong to check if we can do something with it.

**Comment by valeriocos** [comment] 2019-11-08 17:30
Code:
- https://github.com/chaoss/grimoirelab-toolkit/blob/master/grimoirelab_toolkit/datetime.py#L113
- https://github.com/chaoss/grimoirelab-toolkit/blob/master/grimoirelab_toolkit/datetime.py#L131
- https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backends/core/mbox.py#L275

This is in an example of the date:
- 'Wed, 10 Feb 99 10:10:47 EST'

**Comment by sduenas** [comment] 2019-11-11 12:08
Either we have a file including the tzinfo data (I don't know if we can reuse the code someone posted [here](https://gist.github.com/h-j-13/e3a585796510b59601e34a07e99b386d)) or we leave the warning as is. If at some point it raises an exception, we'll catch it.

**Comment by valeriocos** [comment] 2019-11-11 17:39
The list available in the stackoverflow post doesn't seem to be completed. The following date is failing: `Mon, 18 Aug 97 18:33 MET DST`

I would leave the warning or pin the dependency to 2.8.0 (as suggested at https://github.com/chaoss/grimoirelab-elk/issues/722#issuecomment-550343679)

**Comment by sduenas** [comment] 2019-11-12 13:01
> The list available in the stackoverflow post doesn't seem to be completed. The following date is failing: `Mon, 18 Aug 97 18:33 MET DST`
> 
> I would leave the warning or pin the dependency to 2.8.0 (as suggested at [#722 (comment)](https://github.com/chaoss/grimoirelab-elk/issues/722#issuecomment-550343679))

I see. Ok, maybe we can do the best effort possible that would be to include that list (even if it's incomplete). Then we can close this issue as not fixed. If in future version of `dateutil` they raise an exception, we'll catch it and we'll make the conversion to UTC.

What do you think?

**Comment by valeriocos** [comment] 2019-11-12 13:06
I wouldn't include the list. Beyond that, I agree with you, we can close the issue as not fixed, and in the future we will provide the code to handle the exception

**Comment by sduenas** [comment] 2019-11-12 13:16
Ok, then!

**Closed by sduenas** 2019-11-12 13:16 UTC

**Comment by valeriocos** [comment] 2019-11-12 16:21
I transfer the issue to toolkit, the problem should be handled there.
