### ISSUE TITLE
The TypeError using gerrit and p2o.py

### ISSUE THREAD

**Issue by aghassabian** [chaoss/grimoirelab-elk#93] opened 2017-07-28 19:35 UTC
I'm using the p2o.py with the gerrit parameter to retrieve and enrich data from my gerrit repo. but I receive the TypeError in grimoire_elk/ocean/gerrit.py, line 35 

` File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/ocean/gerrit.py", line 35, in _fix_item
    item["ocean-unique-id"] = item["data"]["number"]+"_"+item['origin']
TypeError: unsupported operand type(s) for +: 'int' and 'str'`

Anybody's had the same issue?

**Comment by aghassabian** [comment] 2017-08-04 20:11
Use `item["ocean-unique-id"] = str(item["data"]["number"])+"_"+item['origin']`

**Comment by jgbarah** [comment] 2017-10-31 23:15
Sorry for the delay in answering. Is your Gerrit instance public? If so, could you please provide me with its url, so that I can check and see if I can reproduce the error?

Thanks in advance.

**Comment by valeriocos** [comment] 2018-05-03 09:53
The error reported doesn't appear in our production logs. Given the fact the issue is old, it may be possible that it had been fixed at some point in the past.
Should we close this issue, @jgbarah ?

**Comment by valeriocos** [comment] 2019-07-26 13:13
Closing this issue! For the future, please use micro-mordred (https://github.com/chaoss/grimoirelab-sirmordred#micro-mordred), p2o.py is being decomissioned.

**Closed by valeriocos** 2019-07-26 13:13 UTC
Labels: bug
