### ISSUE TITLE
Error enriching a Git item

### ISSUE THREAD

**Issue by albertinisg** [chaoss/grimoirelab-elk#139] opened 2017-11-29 14:46 UTC
Using `elasticgirl.23`. Traceback:

```
2017-11-27 04:17:42,216 - grimoire_elk.arthur - ERROR - Traceback (most recent call last):
  File "./grimoire_elk/arthur.py", line 445, in enrich_backend
    filter_raw_should)
  File "./grimoire_elk/arthur.py", line 316, in get_ocean_backend
    last_enrich = get_last_enrich(backend_cmd, enrich_backend)
  File "./grimoire_elk/elk/utils.py", line 167, in get_last_enrich
    last_enrich = enrich_backend.get_last_update_from_es([filter_])
  File "./grimoire_elk/elk/enrich.py", line 447, in get_last_update_from_es
    last_update = self.elastic.get_last_date(self.get_incremental_date(), _filters)
  File "./grimoire_elk/elk/elastic.py", line 211, in get_last_date
    last_date = self.get_last_item_field(field, _filters=_filters)
  File "./grimoire_elk/elk/elastic.py", line 264, in get_last_item_field
    res_json = res.json()
  File "/usr/local/lib/python3.4/dist-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)

2017-11-27 04:17:42,231 - grimoire_elk.arthur - ERROR - Error enriching ocean from git (https://github.com/fluent/fluent-plugin-s3.git): Expecting value: line 1 column 1 (char 0)
```

**Comment by sanacl** [comment] 2017-11-29 16:43
@albertinisg I would be more strict with the titles, the first words "Got the following error" add nothing to the topic.

**Comment by acs** [comment] 2017-11-30 06:16
@albertinisg reading the logs, my bet is that Elasticsearch connection has failed and this is why the response from it is not a correct JSON document. Could you replicate the problem? If so, the cause of the error is different.

**Comment by valeriocos** [comment] 2018-05-03 08:55
@acs you were probably right, a connection problem caused this error. 
Since there is no trace of similar errors in the logs, I'm going to close this issue.

**Closed by valeriocos** 2018-05-03 08:55 UTC
Labels: bug
